project:
  type: website

website:
  title: "Global Economic Growth Analysis (2000-2023)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: model.qmd
        text: Model
      - href: trends.qmd
        text: Trends
      - href: sources.qmd
        text: Data Sources
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    self-contained: true
    code-fold: true
    fig-width: 10
    fig-height: 6

execute:
  echo: false
  warning: false
  message: false